<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Plugin.props" />

    <ItemGroup>
        <Compile Include="..\Shared\Track\*.cs" Link="Shared\Track\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Dashboard\index.html" LogicalName="RaceAiPlugin.Dashboard.index.html" />
        <EmbeddedResource Include="Dashboard\driverswap.lua" LogicalName="RaceAiPlugin.Dashboard.driverswap.lua" />
    </ItemGroup>

</Project>
