<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Plugin.props" />

    <ItemGroup>
        <Compile Include="..\Shared\Track\*.cs" Link="Shared\Track\%(Filename)%(Extension)" />
        <Compile Include="..\Shared\Web\*.cs" Link="Shared\Web\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="Pages\admin.html" />
        <EmbeddedResource Include="Pages\admin.html" LogicalName="WebPortalPlugin.Pages.admin.html" />
    </ItemGroup>

</Project>
