<Project Sdk="Microsoft.NET.Sdk">

    <Import Project="..\Plugin.props" />

    <ItemGroup>
        <Compile Include="..\Shared\Track\*.cs" Link="Shared\Track\%(Filename)%(Extension)" />
        <Compile Include="..\Shared\Presets\*.cs" Link="Shared\Presets\%(Filename)%(Extension)" />
        <Compile Include="..\Shared\Web\*.cs" Link="Shared\Web\%(Filename)%(Extension)" />
        <Compile Include="..\Shared\Config\*.cs" Link="Shared\Config\%(Filename)%(Extension)" />
    </ItemGroup>

    <ItemGroup>
        <None Remove="lua\trackchange.lua" />
        <EmbeddedResource Include="lua\trackchange.lua" LogicalName="ServerToolsPlugin.lua.trackchange.lua" />
    </ItemGroup>

</Project>
